name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, closed, reopened]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_TOKEN }}"
          ado_organization: "booksandbooks"
          ado_project: "test"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Resolved"
          ado_bypassrules: true
          log_level: 100
