name: Sync Pull Request to Azure Boards
on:
  pull_request:
    types: [opened, edited, closed]
    branches:
      - master
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-pr-to-work-item@master
        env:
          ado_token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_TOKEN }}"
          ado_organization: "booksandbooks"
          ado_project: "test"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Resolved"
